# Generated by Django 5.0.6 on 2024-07-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_titular', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
                ('hectares', models.FloatField()),
            ],
        ),
    ]
