# Generated by Django 5.0.6 on 2024-08-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0003_rename_loteamento_cutofbanana_local_lot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='img',
            field=models.ImageField(default='img', upload_to=''),
        ),
    ]
