# Generated by Django 5.0.6 on 2024-08-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0004_lots_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutofbanana',
            name='local_lot',
        ),
        migrations.AddField(
            model_name='cutofbanana',
            name='id_lot',
            field=models.IntegerField(default=0),
        ),
    ]
