# Generated by Django 5.0.6 on 2024-08-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0005_remove_cutofbanana_local_lot_cutofbanana_id_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='img',
            field=models.ImageField(default='img/lote.png', upload_to=''),
        ),
    ]
