# Generated by Django 5.0.6 on 2024-08-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0006_alter_lots_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutofbanana',
            name='id_lot',
            field=models.IntegerField(),
        ),
    ]
