# Generated by Django 5.0.6 on 2024-08-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0007_alter_cutofbanana_id_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutofbanana',
            name='kg_caixa',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='cutofbanana',
            name='primeira',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cutofbanana',
            name='segunda',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lots',
            name='hectares',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lots',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
