# Generated by Django 5.0.6 on 2024-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0008_cutofbanana_kg_caixa_alter_cutofbanana_primeira_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutofbanana',
            name='numero_lot',
        ),
        migrations.AlterField(
            model_name='cutofbanana',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
