# Generated by Django 5.0.6 on 2024-08-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0010_alter_cutofbanana_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutofbanana',
            name='porcentagem',
            field=models.FloatField(default=0.0),
        ),
    ]
