# Generated by Django 5.0.6 on 2024-08-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0011_cutofbanana_porcentagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutofbanana',
            name='id_lot',
        ),
        migrations.RemoveField(
            model_name='cutofbanana',
            name='porcentagem',
        ),
    ]
