# Generated by Django 5.0.6 on 2024-08-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0012_remove_cutofbanana_id_lot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutofbanana',
            name='id_lot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cutofbanana',
            name='porcentagem',
            field=models.FloatField(default=0.0),
        ),
    ]
