# Generated by Django 5.0.6 on 2024-12-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0017_cutofbanana_preco_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cutofbanana',
            old_name='data',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='cutofbanana',
            name='cotacao',
        ),
        migrations.RemoveField(
            model_name='cutofbanana',
            name='preco_total',
        ),
        migrations.RemoveField(
            model_name='cutofbanana',
            name='qtd_total',
        ),
    ]
