# Generated by Django 5.0.6 on 2024-12-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0018_rename_data_cutofbanana_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutofbanana',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
    ]
