# Generated by Django 5.0.6 on 2024-12-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0019_cutofbanana_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutofbanana',
            name='cotacao',
            field=models.FloatField(default=0.0),
        ),
    ]
